### ISSUE TITLE
Failed to send pm2 data to Zabbix server getting "code":1

### ISSUE THREAD

**Issue by nshah14285** [greatcare/pm2-zabbix#45]
Hello,

Not able to send pm2 processes to the Zabbix server using pm2-zabbix. Getting below error.
It was working fine with Ubuntu 16.04. After upgrading to Ubuntu  18.04 it stopped working.
How to fix it? Any idea?

Zabbix server: 4.0.9
Zabbix agent: 4.0.22
Ubuntu: 18.04
OPENSSL: 1.1.1g
GNUTLS: 3.5.18

**Zabbix Agent Conf:**

TLSConnect=psk
TLSAccept=psk
TLSPSKIdentity=PSK 001
TLSPSKFile=/etc/zabbix/zabbix_agentd.psk

**zabbix-agent log**

`SSL_shutdown() with zabbix.server set result code to 1: file ../ssl/ssl_lib.c line 2086: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init
 20356:20200704:182146.522 active check configuration update from [mon.leapven.com:15001] started to fail (TLS read set result code to 1: file ../ssl/record/rec_layer_s3.c line 1544: error:1409445C:SSL routines:ssl3_read_bytes:tlsv13 alert certificate required: SSL alert number 116: TLS read fatal alert "unknown")
 20356:20200704:182146.522 End of refresh_active_checks():FAIL`

**pm2-zabbix Error:**

`{"name":"pm2-zabbix","hostname":"test","pid":25087,"level":50,"event":"PM2ZabbixMonitor#processListSendingError","error":{"killed":false,"code":1,"signal":null,"cmd":"/usr/bin/zabbix_sender --config /etc/zabbix/zabbix_agentd.conf --input-file -"},"msg":"Failed to send process list with stats to server: Error: Command failed: /usr/bin/zabbix_sender --config /etc/zabbix/zabbix_agentd.conf --input-file -\n\n    at ChildProcess.exithandler (child_process.js:303:12)\n    at ChildProcess.emit (events.js:315:20)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Socket.<anonymous> (internal/child_process.js:443:11)\n    at Socket.emit (events.js:315:20)\n    at Pipe.<anonymous> (net.js:674:12) {\n  killed: false,\n  code: 1,\n  signal: null,\n  cmd: '/usr/bin/zabbix_sender --config /etc/zabbix/zabbix_agentd.conf --input-file -'\n}","time":"2020-07-07T14:27:45.263Z","v":0}`

**Comment by intensite** [comment]
I am facing the same issue. 
Were you able to find what was causing this problem?
